"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";

type PaymentMethod =
  | "upi"
  | "card"
  | "netbanking"
  | "wallet";

type PendingBooking = {
  bookingCode: string;
  eventNumber?: string;
  eventId?: string;
  title: string;
  date: string;
  location: string;
  venue: string;
  time?: string;
  seats: string[];
  price: number;
  total: number;
  quantity?: number;
  returnPath?: string;
};

export default function PaymentPage() {
  const router = useRouter();

  const [paymentMethod, setPaymentMethod] =
    useState<PaymentMethod>("upi");

  const [upiId, setUpiId] = useState("");
  const [cardNumber, setCardNumber] = useState("");
  const [expiry, setExpiry] = useState("");
  const [cvv, setCvv] = useState("");

  const [pendingBooking, setPendingBooking] =
    useState<PendingBooking | null>(null);

  const [isProcessing, setIsProcessing] =
    useState(false);

  /*
   * =====================================================
   * LOAD PENDING BOOKING
   * =====================================================
   *
   * TicketDrawer creates this before sending the
   * user to /payment.
   */

  useEffect(() => {
    try {
      const stored =
        sessionStorage.getItem(
          "seatwise-pending-payment"
        );

      if (!stored) {
        return;
      }

      const parsed = JSON.parse(stored);

      if (
        parsed &&
        Array.isArray(parsed.seats)
      ) {
        setPendingBooking(parsed);
      }
    } catch (error) {
      console.error(
        "Unable to load pending booking:",
        error
      );
    }
  }, []);

  /*
   * =====================================================
   * FALLBACK VALUES
   * =====================================================
   *
   * These only prevent the UI from becoming broken if
   * somebody directly opens /payment.
   */

  const ticketPrice =
    pendingBooking?.price ?? 899;

  const convenienceFee = 0;

  const ticketQuantity =
    pendingBooking?.seats?.length ??
    pendingBooking?.quantity ??
    1;

  const total =
    pendingBooking?.total ??
    ticketPrice * ticketQuantity +
      convenienceFee;


  /*
   * =====================================================
   * MOCK PAYMENT
   * =====================================================
   *
   * For now:
   *
   * - No real payment gateway
   * - No validation
   * - Any input is accepted
   *
   * After successful mock payment:
   *
   * PAYMENT
   *    ↓
   * EVENT PAGE
   *    ↓
   * EXISTING DRAWER
   *    ↓
   * PRINTING ANIMATION
   *    ↓
   * CONFIRMED TICKET
   *
   * No automatic My Tickets redirect.
   */

  const handleMockPayment = () => {
    if (isProcessing) {
      return;
    }

    if (!pendingBooking) {
      return;
    }

    setIsProcessing(true);

    try {
      /*
       * Generate a booking code if one wasn't
       * already generated by TicketDrawer.
       */

      const bookingCode =
        pendingBooking.bookingCode ||
        "SW26-" +
          Math.random()
            .toString(36)
            .substring(2, 8)
            .toUpperCase();

      /*
       * Pass the successful payment information
       * back to TicketDrawer.
       *
       * IMPORTANT:
       * This does NOT save the booking here.
       * TicketDrawer will save it after payment
       * succeeds and before the printing animation.
       */

      const paymentSuccess = {
        ...pendingBooking,
        bookingCode,
        paymentStatus: "success",
        paidAt: new Date().toISOString(),
      };

      sessionStorage.setItem(
        "seatwise-payment-success",
        JSON.stringify(paymentSuccess)
      );

      /*
       * Remove temporary pending state.
       */

      sessionStorage.removeItem(
        "seatwise-pending-payment"
      );

      /*
       * Small delay so the payment button has
       * a proper processing state.
       */

      setTimeout(() => {
        /*
         * Return to the EXACT event-detail page that
         * started this booking.
         *
         * router.back() could restore /events instead of
         * the event-detail page that owns TicketDrawer.
         */
        const returnPath =
          pendingBooking.returnPath || "/events";

        /*
         * Replace /payment with the event page.
         * This keeps the browser flow clean:
         *
         * EVENT
         *   ↓
         * PAYMENT
         *   ↓
         * SAME EVENT + TICKET DRAWER
         *
         * TicketDrawer then shows:
         * PRINTING → TICKET/BILL → DONE
         */
        router.replace(returnPath);
      }, 600);
    } catch (error) {
      console.error(
        "SeatWise mock payment failed:",
        error
      );

      setIsProcessing(false);
    }
  };


  return (
    <main className="payment-page">

      {/* =====================================================
          HEADER
      ===================================================== */}

      <header className="payment-header">

        <Link
          href="/"
          className="payment-brand"
        >
          SEATWISE<sup>®</sup>
        </Link>

        <span className="payment-edition">
          IND / 2026
        </span>

        <Link
          href="/events"
          className="payment-back"
        >
          ← BACK
        </Link>

      </header>


      {/* =====================================================
          MAIN
      ===================================================== */}

      <section className="payment-main">

        {/* ===================================================
            LEFT — BOOKING INFORMATION
        =================================================== */}

        <div className="payment-intro">

          <span className="payment-eyebrow">
            04 / COMPLETE YOUR BOOKING
          </span>

          <h1>
            SECURE
            <br />
            YOUR
            <br />
            <span>PLACE.</span>
          </h1>

          <p className="payment-description">
            COMPLETE YOUR PAYMENT TO CONFIRM YOUR
            SEAT AND EXPERIENCE.
          </p>


          {/* =================================================
              EVENT CARD
          ================================================= */}

          <div className="payment-event">

            <div className="payment-event-top">

              <span>
                {pendingBooking?.eventNumber ||
                  "01"}{" "}
                / EVENT
              </span>

              <span>
                LIVE EXPERIENCE
              </span>

            </div>


            <h2>
              {pendingBooking?.title ||
                "The Last Light"}
            </h2>


            <div className="payment-event-details">

              <div>

                <small>
                  DATE / TIME
                </small>

                <strong>
                  {pendingBooking?.date ||
                    "22 AUG"}{" "}
                  /{" "}
                  {pendingBooking?.time ||
                    "08:00 PM"}
                </strong>

              </div>


              <div>

                <small>
                  LOCATION
                </small>

                <strong>
                  {pendingBooking?.location ||
                    "Delhi"}{" "}
                  /{" "}
                  {pendingBooking?.venue ||
                    "Kamani Auditorium"}
                </strong>

              </div>

            </div>


            <div className="payment-event-bottom">

              <div>

                <small>
                  YOUR SEAT
                </small>

                <strong>
                  {pendingBooking?.seats?.join(
                    " · "
                  ) || "A1"}
                </strong>

              </div>


              <div>

                <small>
                  TICKETS
                </small>

                <strong>
                  {String(
                    ticketQuantity
                  ).padStart(2, "0")}
                </strong>

              </div>

            </div>

          </div>


          {/* =================================================
              EDITORIAL FOOTER
          ================================================== */}

          <div className="payment-intro-footer">

            <span>
              DISCOVER
            </span>

            <span>
              BOOK
            </span>

            <span>
              BE THERE
            </span>

          </div>

        </div>


        {/* ===================================================
            RIGHT — PAYMENT PANEL
        =================================================== */}

        <div className="payment-panel">


          {/* =================================================
              PANEL HEADER
          ================================================== */}

          <div className="payment-panel-header">

            <div>

              <span>
                PAYMENT
              </span>

              <h2>
                SECURE CHECKOUT
              </h2>

            </div>

            <span className="payment-number">
              01
            </span>

          </div>


          {/* =================================================
              PAYMENT METHODS
          ================================================== */}

          <div className="payment-methods">

            {/* UPI */}

            <button
              type="button"
              className={
                paymentMethod === "upi"
                  ? "payment-method active"
                  : "payment-method"
              }
              onClick={() =>
                setPaymentMethod("upi")
              }
            >

              <span>
                01
              </span>

              <strong>
                UPI
              </strong>

              <em>
                ↗
              </em>

            </button>


            {/* CARD */}

            <button
              type="button"
              className={
                paymentMethod === "card"
                  ? "payment-method active"
                  : "payment-method"
              }
              onClick={() =>
                setPaymentMethod("card")
              }
            >

              <span>
                02
              </span>

              <strong>
                CARD
              </strong>

              <em>
                ↗
              </em>

            </button>


            {/* NET BANKING */}

            <button
              type="button"
              className={
                paymentMethod ===
                "netbanking"
                  ? "payment-method active"
                  : "payment-method"
              }
              onClick={() =>
                setPaymentMethod(
                  "netbanking"
                )
              }
            >

              <span>
                03
              </span>

              <strong>
                NET BANKING
              </strong>

              <em>
                ↗
              </em>

            </button>


            {/* WALLET */}

            <button
              type="button"
              className={
                paymentMethod === "wallet"
                  ? "payment-method active"
                  : "payment-method"
              }
              onClick={() =>
                setPaymentMethod("wallet")
              }
            >

              <span>
                04
              </span>

              <strong>
                WALLET
              </strong>

              <em>
                ↗
              </em>

            </button>

          </div>


          {/* =================================================
              PAYMENT FORM
          ================================================== */}

          <div className="payment-form">


            {/* =================================================
                UPI
            ================================================== */}

            {paymentMethod === "upi" && (

              <div className="payment-method-content">

                <div className="payment-content-heading">

                  <span>
                    01 / UPI PAYMENT
                  </span>

                  <p>
                    Enter your UPI ID to continue.
                  </p>

                </div>


                <label className="payment-field">

                  <span>
                    UPI ID
                  </span>

                  <input
                    type="text"
                    placeholder="YOURNAME@UPI"
                    value={upiId}
                    onChange={(event) =>
                      setUpiId(
                        event.target.value
                      )
                    }
                  />

                </label>


                <div className="payment-upi-note">

                  <span>
                    ✓
                  </span>

                  <p>
                    You will be redirected to
                    your UPI application to
                    approve the payment.
                  </p>

                </div>

              </div>

            )}


            {/* =================================================
                CARD
            ================================================== */}

            {paymentMethod === "card" && (

              <div className="payment-method-content">

                <div className="payment-content-heading">

                  <span>
                    02 / CARD PAYMENT
                  </span>

                  <p>
                    Enter your card details securely.
                  </p>

                </div>


                <label className="payment-field">

                  <span>
                    CARD NUMBER
                  </span>

                  <input
                    type="text"
                    inputMode="numeric"
                    maxLength={19}
                    placeholder="0000 0000 0000 0000"
                    value={cardNumber}
                    onChange={(event) =>
                      setCardNumber(
                        event.target.value
                      )
                    }
                  />

                </label>


                <div className="payment-field-row">

                  <label className="payment-field">

                    <span>
                      EXPIRY
                    </span>

                    <input
                      type="text"
                      placeholder="MM / YY"
                      maxLength={7}
                      value={expiry}
                      onChange={(event) =>
                        setExpiry(
                          event.target.value
                        )
                      }
                    />

                  </label>


                  <label className="payment-field">

                    <span>
                      CVV
                    </span>

                    <input
                      type="password"
                      placeholder="•••"
                      maxLength={3}
                      value={cvv}
                      onChange={(event) =>
                        setCvv(
                          event.target.value
                        )
                      }
                    />

                  </label>

                </div>

              </div>

            )}


            {/* =================================================
                NET BANKING
            ================================================== */}

            {paymentMethod ===
              "netbanking" && (

              <div className="payment-method-content">

                <div className="payment-content-heading">

                  <span>
                    03 / NET BANKING
                  </span>

                  <p>
                    Select your preferred bank.
                  </p>

                </div>


                <label className="payment-field">

                  <span>
                    SELECT BANK
                  </span>

                  <select defaultValue="">

                    <option
                      value=""
                      disabled
                    >
                      SELECT YOUR BANK
                    </option>

                    <option>
                      STATE BANK OF INDIA
                    </option>

                    <option>
                      HDFC BANK
                    </option>

                    <option>
                      ICICI BANK
                    </option>

                    <option>
                      AXIS BANK
                    </option>

                    <option>
                      OTHER BANK
                    </option>

                  </select>

                </label>

              </div>

            )}


            {/* =================================================
                WALLET
            ================================================== */}

            {paymentMethod ===
              "wallet" && (

              <div className="payment-method-content">

                <div className="payment-content-heading">

                  <span>
                    04 / WALLET
                  </span>

                  <p>
                    Choose a wallet to continue.
                  </p>

                </div>


                <div className="wallet-options">

                  <button type="button">
                    PAYTM
                  </button>

                  <button type="button">
                    PHONEPE
                  </button>

                  <button type="button">
                    AMAZON PAY
                  </button>

                </div>

              </div>

            )}

          </div>


          {/* =================================================
              PRICE SUMMARY
          ================================================== */}

          <div className="payment-summary">

            <div className="payment-summary-row">

              <span>
                {ticketQuantity} × TICKET
              </span>

              <strong>
                ₹
                {(
                  ticketPrice *
                  ticketQuantity
                ).toLocaleString("en-IN")}
              </strong>

            </div>


            <div className="payment-summary-row">

              <span>
                CONVENIENCE FEE
              </span>

              <strong>
                ₹{convenienceFee}
              </strong>

            </div>


            <div className="payment-summary-total">

              <span>
                TOTAL
              </span>

              <strong>
                ₹
                {total.toLocaleString(
                  "en-IN"
                )}
              </strong>

            </div>

          </div>


          {/* =================================================
              PAY BUTTON
          ================================================== */}

          <button
            type="button"
            className="payment-submit"
            onClick={handleMockPayment}
            disabled={
              isProcessing ||
              !pendingBooking
            }
          >

            <span>
              {isProcessing
                ? "PROCESSING..."
                : `PAY ₹${total}`}
            </span>

            <span>
              {isProcessing
                ? "..."
                : "↗"}
            </span>

          </button>


          {/* =================================================
              SECURITY
          ================================================== */}

          <div className="payment-security">

            <span>
              SECURE PAYMENT
            </span>

            <span>
              SEATWISE®
            </span>

          </div>

        </div>

      </section>


      {/* =====================================================
          FOOTER
      ===================================================== */}

      <footer className="payment-footer">

        <span>
          SEATWISE®
        </span>

        <span>
          DISCOVER / BOOK / BE THERE
        </span>

        <span>
          © 2026
        </span>

      </footer>

    </main>
  );
}